name: ToDo Bot

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy using SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/bot/task_daylist
          git pull origin master
          git status
          systemctl stop task_daylist
          systemctl daemon-reload
          systemctl enable task_daylist
          systemctl start task_daylist
